server:
  port: 8080
camel:
  health:
    enabled: true
  springboot:
    name: ServicesRest
management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
